### ISSUE TITLE
Gmail SMTP is not working

### ISSUE THREAD

**Issue by raphaelsimon1** [bhattsameer/Bombers#110]
Please advise if another email can be used and if only gmail how to bypass that error especially less secure apps option is not working anymore.

Error Message:

Traceback (most recent call last):
  File "/Users/fadykhella/Documents/GitHub/Bombers/Email_Bomber_Version2.py", line 25, in <module>
    mail.login(email,password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
**smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials p2-20020a05600c358200b003942a244f47sm19046737wmq.32 - gsmtp')**

**Comment by ClaytonBen** [comment]
You need to use this:

https://stackoverflow.com/questions/57715289/how-to-fix-ssl-sslerror-ssl-wrong-version-number-wrong-version-number-ssl
