### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by rockydares** [bhattsameer/Bombers#22]
Getting error while running, what am I doing wrong?

#sudo python3 SMS-bomber.py

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/Bombers/SMS_bomber.py", line 41, in <module>
    for i in range(how_many):
TypeError: 'str' object cannot be interpreted as an integer

**Comment by he1ox** [comment]
you dont need sudo everytime you run that code.
Im gettin that issue too.
